// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrrnzuncgcognqcvjwxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpycm56dW5jZ2NvZ25xY3Zqd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODU3MzYsImV4cCI6MjA2MjY2MTczNn0.h7b1Hk_Ji3KDrx4cWWtM7wagUbcyhTHbVdw0UdfE5t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);